### ISSUE TITLE
Multichange isn't respecting case sensitivity

### ISSUE THREAD

**Issue by rgrinberg** [AndrewRadev/multichange.vim#1]
Consider the following buffer (or selection)

```
event
Event
event 
```

Running multichange and changing `event` will also change the 2nd line `Event`. To me that is unexpected and undesirable. Would be great to at least be able to toggle this option.

**Comment by AndrewRadev** [comment]
You're right, it seems odd that it would change words with different casing. The reason is that you probably have `ignorecase` or `smartcase` on, and the plugin just does a normal search, which respects those.

I've pushed a commit that forces case-sensitivity, let me know if it fixes the issue.

**Comment by AndrewRadev** [comment]
I think this should fix the issue, so I'll go ahead and close this for now. Do reopen it if it doesn't seem to work for you.
