### ISSUE TITLE
Issue with duplication when the replacement expands upon the word

### ISSUE THREAD

**Issue by thalesmello** [AndrewRadev/multichange.vim#4]
Suppose you have the following snippet.

```
" Denite
Plug 'Shougo/denite.nvim'
Plug 'chemzqm/unite-location'
Plug 'thalesmello/config-unite-outline'
Plug 'Shougo/unite-outline'
```

And you want to replace the word `Plug`. You type `cwPlug More`, but it gets replaced by

```
" Denite
Plug More More 'Shougo/denite.nvim'
Plug More 'chemzqm/unite-location'
Plug More 'thalesmello/config-unite-outline'
Plug More 'Shougo/unite-outline'
```

From another thread, @AndrewRadev said:

> As for the duplicated content, this one is trickier. The plugin runs a substitution to do the replacement, and when you replace, say "foo" with "foo bar", it tries to replace any "foo" in the range with "foo bar". And since you've already typed "foo bar", your just-typed "foo" gets replaced as well. One possibility is to add the line and column in some sort of negative-lookbehind pattern, and I've tried to do that in the past (and also just now), but it got complicated. I'll see what I can do.

What about you let the user change the text, you get the text that was just replaced, undo the operation, so the text goes back to the initial position, and then you apply the substitution?

**Comment by AndrewRadev** [comment]
Hmm, that actually sounds like a pretty good idea. I'll try it out, see if it works.

**Comment by AndrewRadev** [comment]
You were right, a single `undo` seems to fix the issue nicely :). I should have thought of that myself, really, thank you very much for giving me the idea.

That said, I can't be 100% sure it won't break something strange. I've pushed the change to master, could you try it out, see if it seems to work for you?

**Comment by thalesmello** [comment]
:+1: it works as expected.
