### ISSUE TITLE
Don't touch user's matchadd() definitions

### ISSUE THREAD

**Issue by amerlyq** [AndrewRadev/multichange.vim#6]
After leaving `MULTI` mode, all user's highlightings added by matchadd() disappearch.
Maybe replace current reset method by smth alike to https://github.com/t9md/vim-quickhl ?

**Comment by AndrewRadev** [comment]
I tried to use `2match` instead, I think that's what vim-quickhl does internally. Could you try it out and see if it works better for you now?

**Comment by amerlyq** [comment]
I have tried new version. On first glance, no regressions found. Thanks.
