### ISSUE TITLE
Alternative by interactive substitution

### ISSUE THREAD

**Issue by amerlyq** [AndrewRadev/multichange.vim#7]
It's not really issue, only notice for history purposes how to do the same in other way. Feel free to close.

Default vim way is straight, but possible patterns to choose are restricted in many ways:
* `*/#` to set pattern
* `vip` to select range
* `:s//newname/g` to rename

More nice alternative combo, used by me until today: 
* https://github.com/haya14busa/vim-asterisk 
* https://github.com/osyo-manga/vim-over.

First plugin extends possible choices for `*/#` to set patterns in many cases. 
And second one has nice in-place visual feedback on all replacements.

**Comment by AndrewRadev** [comment]
Thank you, I've added a note about these in the README.
